# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Create Maven Master Password
      id: set_master_password
      run: echo "MVN_MASTER_PASS=$(mvn --encrypt-master-password '${{secrets.MAVEN_MASTER_PASSWORD}}')" >> $GITHUB_OUTPUT
    - name: Create Maven settings-security.xml
      run: echo "<settingsSecurity><master>${{steps.set_master_password.outputs.MVN_MASTER_PASS}}</master></settingsSecurity>" > ~/.m2/settings-security.xml
    - name: Encrypt Anypoint Platform Password
      id: encrypt_ap_pass
      run: echo "ANYPOINT_PASSWORD_ENCRYPTED=$(mvn --encrypt-password '${{secrets.ANYPOINT_PASSWORD}}')" >> $GITHUB_OUTPUT
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: >
          [
            {
              "id": "anypoint-exchange-v2",
              "username": "${{secrets.ANYPOINT_USER}}",
              "password": "${{steps.encrypt_ap_pass.outputs.ANYPOINT_PASSWORD_ENCRYPTED}}"
            },
            {
              "id": "anypoint-exchange-v3",
              "username": "${{secrets.ANYPOINT_USER}}",
              "password": "${{steps.encrypt_ap_pass.outputs.ANYPOINT_PASSWORD_ENCRYPTED}}"
            }
          ]
        mirrors: >
          [
            {
              "id": "maven-default-http-blocker",
              "mirrorOf": "dummy",
              "url": "http://0.0.0.0/"
            }
          ]
        repositories: '[{ "id": "anypoint-exchange-v3", "url": "https://maven.anypoint.mulesoft.com/api/v3/organizations/58352764-d415-4032-8943-d794cfb602ba/maven" }]'
    - name: View settings.xml
      run: cat /home/runner/.m2/settings.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
